[tools]
elm = "0.19.2"
node = "26.5.0"
"github:mpizenberg/elm-test-rs" = "3.2.0"
"github:avh4/elm-format" = "0.8.8"

[tasks.test]
run = "elm-test-rs"

[tasks.build]
run = "elm make src/ListDate.elm --output /dev/null"

[tasks.format]
run = "elm-format --validate src/ tests/"
